Create crop-for-coins.md
SkyKings-Guild/Guides pull request #22
Opened 2023-10-05 20:22 UTC by minoyahia

## Summary

## Information

- [x] This PR fixes a formatting issue.
- [x] This PR corrects the information in an existing guide.
- [x] This PR adds a new guide.

## Checklist

- [x] I have searched the open pull requests for duplicates.
- [x] I am sure the guide is formatted properly.

## Licensing

- [x] I agree that my contributions shall be licensed under the [Creative Commons Attribution-ShareAlike 4.0 International License](https://creativecommons.org/licenses/by-sa/4.0/),
  and that SkyKings may distribute my contributions under the same license on their website.

2023-10-05 21:19 UTC, plun1331 requested changes

2023-10-05 21:19 UTC, plun1331 commented on guides/crop-for-coins.md
> +to make the most? well then, you came to the right place!
```suggestion
to make the most? Well then, you came to the right place!
```

2023-10-05 21:19 UTC, plun1331 commented on guides/crop-for-coins.md
> +over elephant, but you'll be going to loose quite the amount of collection.
what

2023-10-05 21:19 UTC, plun1331 commented on guides/crop-for-coins.md
> +getting the most amount of coins, ranking as best with a potentail 16m per hour
```suggestion
While using bountiful with a decent setup and a melon dicer, you'll be 
getting the most amount of coins, ranking as best with a potential 16m per hour
```

2023-10-06 09:25 UTC, minoyahia commented on guides/crop-for-coins.md
> +over elephant, but you'll be going to loose quite the amount of collection.
yes

2023-10-07 13:04 UTC, minoyahia reviewed
smash

2023-10-17 22:01 UTC, merged