Create garden
SkyKings-Guild/Guides pull request #3
Opened 2023-04-23 04:05 UTC by djjxx1

## Summary

## Information

- [ ] This PR fixes a formatting issue.
- [ ] This PR corrects the information in an existing guide.
- [ ] This PR adds a new guide.

## Checklist

- [ ] I have searched the open pull requests for duplicates.
- [ ] I am sure the guide is formatted properly.

## Licensing

- [ ] I agree that my contributions shall be licensed under the [Creative Commons Attribution-ShareAlike 4.0 International License](https://creativecommons.org/licenses/by-sa/4.0/),
  and that SkyKings may distribute my contributions under the same license on their website.

2023-04-25 14:23 UTC, plun1331 commented
@djjxx1 Please check the "Licensing" box in your PR description

2023-04-27 19:06 UTC, M4axim requested changes
Please correct alwways to always

2023-04-27 22:08 UTC, DaytonWallace approved these changes, later dismissed

2023-04-27 22:49 UTC, plun1331 requested changes

2023-04-27 22:49 UTC, plun1331 commented on guides/garden.md
> +Part 1: Leveling up your Garden
```suggestion
## Part 1: Leveling up your Garden
```

2023-04-27 22:49 UTC, plun1331 commented on guides/garden.md
> +Part 1.5: Visitors
```suggestion
### Visitors
```

2023-04-27 22:49 UTC, plun1331 commented on guides/garden.md
> +To level up your garden you need to one, unlock crop milestones, or two, complete visitor offers. At the start, you should
```suggestion
To level up your garden you need to either unlock crop milestones or complete visitor offers. At the start, you should
```

2023-04-27 22:49 UTC, plun1331 commented on guides/garden.md
> +With visitors, you should accept all of the unique visitors, thevisitors with cheep offers, legendarys (they are
```suggestion
With visitors, you should accept all of the unique visitors, visitors with cheap offers, legendaries (they are 
```

2023-04-27 22:49 UTC, plun1331 commented on guides/garden.md
> +profit almost all of the time) and visitors that have crops you can farm.Getting to garden 10 is pretty easy but every
```suggestion
profit almost all of the time) and visitors that have crops you can farm. Getting to garden 10 is pretty easy but every 
```

2023-04-27 22:49 UTC, plun1331 commented on guides/garden.md
> +Part 2: Money Making Methods
```suggestion
## Part 2: Money Making Methods
```

2023-04-27 22:49 UTC, plun1331 commented on guides/garden.md
> +decent price. Other crops still make a lot of money but nether wart is the best The second money making method is
```suggestion
decent price. Other crops still make a lot of money but nether wart is the best.

The second money making method is
```

2023-04-27 22:49 UTC, plun1331 commented on guides/garden.md
> +going for decently high prices. The third and final money making method of this guide is farming mushrooms for
```suggestion
going for decently high prices. 

The third and final money making method of this guide is farming mushrooms for
```

2023-04-27 22:49 UTC, plun1331 commented on guides/garden.md
> +Part 3: The Composter
```suggestion
## The Composter
```

2023-04-27 22:51 UTC, plun1331 approved these changes

2023-04-27 22:59 UTC, DaytonWallace approved these changes

2023-04-27 22:59 UTC, merged