Create blaze.md
SkyKings-Guild/Guides pull request #4
Opened 2023-04-28 10:44 UTC by djjxx1

## Summary

## Information

- [ ] This PR fixes a formatting issue.
- [ ] This PR corrects the information in an existing guide.
- [ ] This PR adds a new guide.

## Checklist

- [ ] I have searched the open pull requests for duplicates.
- [ ] I am sure the guide is formatted properly.

## Licensing

- [ ] I agree that my contributions shall be licensed under the [Creative Commons Attribution-ShareAlike 4.0 International License](https://creativecommons.org/licenses/by-sa/4.0/),
  and that SkyKings may distribute my contributions under the same license on their website.

2023-04-28 13:27 UTC, DaytonWallace requested changes
Move blaze.md into the guides folder

2023-04-28 14:57 UTC, M4axim requested changes
Please fix Reccomended to Rcommended

2023-04-28 15:29 UTC, plun1331 requested changes

2023-04-28 15:29 UTC, plun1331 commented on guides/blaze.md
> +slayer
```suggestion
tags:
  - blaze
  - inferno
  - slayer
```

2023-04-28 15:29 UTC, plun1331 commented on guides/blaze.md
> +So you're struggling with blaze slayer? Well, you have came to the right place! Here you will learn how to defeat all tiers of blaze slayer
```suggestion

So you're struggling with blaze slayer? Well, you have come to the right place! Here you will learn how to defeat all tiers of blaze slayer
```

2023-04-28 15:29 UTC, plun1331 commented on guides/blaze.md
> +Part 1: Gear Requirements
```suggestion
## Part 1: Gear Requirements
```

2023-04-28 15:29 UTC, plun1331 commented on guides/blaze.md
> +Tier 1
```suggestion
### Tier 1
```

2023-04-28 15:29 UTC, plun1331 commented on guides/blaze.md
> +Tier 2
```suggestion
### Tier 2
```

2023-04-28 15:29 UTC, plun1331 commented on guides/blaze.md
> +Tier 3
```suggestion
### Tier 3
```

2023-04-28 15:29 UTC, plun1331 commented on guides/blaze.md
> +Tier 4
```suggestion
### Tier 4
```

2023-04-28 15:29 UTC, plun1331 commented on guides/blaze.md
> +Part 2: Places to spawn and cheese
```suggestion
## Part 2: Places to spawn and cheese
```

2023-04-28 15:29 UTC, plun1331 commented on guides/blaze.md
> +Pet(s): Legendary Griffin (Cheep), Legendary Enderdragon (Reccomended),  Wolf/Wisp (Spawning)
```suggestion
Pet(s): Legendary Griffin (Cheap), Legendary Enderdragon (Recommended), Wolf/Wisp (Spawning)
```

2023-04-28 15:29 UTC, plun1331 commented on guides/blaze.md
> +Pet(s): Legedary Griffin (Reccomended), Wolf/Wisp (Spawning)
```suggestion
Pet(s): Legendary Griffin (Recommended), Wolf/Wisp (Spawning)
```

2023-04-28 15:29 UTC, plun1331 commented on guides/blaze.md
> +Pet(s): Rare Lion (shelmet is reccomended)
```suggestion
Pet(s): Rare Lion (shelmet is recommended)
```

2023-04-28 21:49 UTC, plun1331 approved these changes, later dismissed

2023-04-29 02:12 UTC, DaytonWallace approved these changes

2023-04-29 04:08 UTC, plun1331 approved these changes

2023-04-29 04:08 UTC, merged