Update kuudra.md
SkyKings-Guild/Guides pull request #40
Opened 2024-04-09 07:28 UTC by localneoguy

corrections

## Summary

## Information

- [ ] This PR fixes a formatting issue.
- [ ] This PR corrects the information in an existing guide.
- [ ] This PR adds a new guide.

## Checklist

- [ ] I have searched the open pull requests for duplicates.
- [ ] I am sure the guide is formatted properly.

## Licensing

- [ ] I agree that my contributions shall be licensed under the [Creative Commons Attribution-ShareAlike 4.0 International License](https://creativecommons.org/licenses/by-sa/4.0/),
  and that SkyKings may distribute my contributions under the same license on their website.

2024-04-09 13:06 UTC, plun1331 requested changes
Please actually fill out the PR template (it's just check boxes)

2024-04-09 13:06 UTC, plun1331 commented on guides/kuudra.md
> +also Jeff is RNG carried Remember ( jk he helped me with stuffs )
We don't put credits at the bottom of our guides, you are credited in the copyright section at the end of the guide
```suggestion
```

2024-04-09 15:10 UTC, localneoguy commented
which one?

2024-04-09 15:10 UTC, localneoguy commented
its not letting me click

2024-04-10 04:16 UTC, plun1331 approved these changes

2024-04-10 04:17 UTC, merged